In [7]:
import numpy as np
import time

In [2]:
x = [84, 82, -999, -1, 54, 52]

In [4]:
np.array(x)

array([  84,   82, -999,   -1,   54,   52])

In [3]:
np.array(x).reshape(1, -1)

array([[  84,   82, -999,   -1,   54,   52]])

In [10]:
lst = [1, 7, 0, 6, 2, 5, 6]
arr = np.asarray(lst)
type(lst), type(arr)

(list, numpy.ndarray)

In [16]:
list1 = [1,2,3] 
list2 = [4,5,6]

# Create List of lists 
_l = [list1, list2]

# Display result
type(_l), type(_l[0])

ar = np.array(_l)

type(ar), type(ar[0])

(numpy.ndarray, numpy.ndarray)

In [17]:
%%time
# dot product
tic = time.time()
w = np.random.rand(100000)
x = np.random.rand(100000)
print(np.dot(w, x))
toc = time.time()
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

25045.877506769437
loop version duration: 2.1729 ms 
CPU times: user 3.76 ms, sys: 2.33 ms, total: 6.09 ms
Wall time: 2.25 ms


In [18]:
%%time
tic = time.time()
f = 0
for j in range(100000):
    f += w[j] * x[j]
print(f)
toc = time.time()
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

25045.877506770128
loop version duration: 41.1720 ms 
CPU times: user 40.9 ms, sys: 1.55 ms, total: 42.4 ms
Wall time: 41.2 ms


In [19]:
type(w)

numpy.ndarray

In [5]:
# vstack(): stack the sequence of input arrays vertically to make a single array.

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays vertically, the must have the same amount of cols.
# put them in tup.
out_arr = np.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [7]:
# vectorize()

def myfunc(a, b):
    if a > b:
        return a - b
    else:
        return a + b
    
vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4, 5], 2)

array([3, 4, 1, 2, 3])

In [11]:
# unique()
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
nums, index, counts = np.unique(a, return_index=True, return_counts=True)
print(nums)
print(index)
print(counts)

[2 5 6 7 8 9]
[1 0 2 4 7 9]
[3 2 2 1 1 1]


In [8]:
# ravel: Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8]])
np.ravel(x)

/var/folders/97/xh2xjk0907j3n7xxd2p_z4x40000gq/T/ipykernel_83308/2263225985.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[1, 2, 3], [4, 5, 6], [7, 8]])


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8])], dtype=object)

In [11]:
# concatenate
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [13]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# m

In [3]:
in_arr1 = np.array([[2, -7, 5], [-6, 2, 0]])
in_arr2 = np.array([[0, -7, 8], [5, -2, 9]])
   
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)
   
    
out_arr = np.multiply(in_arr1, in_arr2) 
print ("Resultant output array: ", out_arr) 

1st Input array :  [[ 2 -7  5]
 [-6  2  0]]
2nd Input array :  [[ 0 -7  8]
 [ 5 -2  9]]
Resultant output array:  [[  0  49  40]
 [-30  -4   0]]


# p

In [3]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [5]:
np.percentile(a, 50), np.percentile(a, 99)

(3.5, 9.850000000000001)

In [6]:
# it treat 1d and 2d the same.
b = np.array([[10, 7, 4, 3, 2, 1]])
b

array([[10,  7,  4,  3,  2,  1]])

In [7]:
np.percentile(b, 50), np.percentile(b, 99)

(3.5, 9.850000000000001)

# t

In [4]:
arr = np.arange(60).reshape(6, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [5]:
arr.transpose()

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])

In [6]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])